### PR TITLE
Updated hasPlacementContext restrictions on Sensor capabilities

### PR DESCRIPTION
**Pull request by hammar**
Based on description by @erikoskarwallin

### CODE REVIEW

**Comment by erikoskarwallin** [comment]
ok

**Comment by erikoskarwallin** [comment]
One thing: the change from "IndoorAir" to "Air" needs to be backwards compatible (same for "Outdoor")

**Comment by hammar** [comment]
> One thing: the change from "IndoorAir" to "Air" needs to be backwards compatible (same for "Outdoor")

Good catch @erikoskarwallin, I've now complemented the pull request with such backwards compatibility, see latest commit above.

**Comment by hammar** [comment]
This PR is deprecated by more recent developments in REC-DTDL.

**Pull request closed without merging**
