### PR TITLE
Add quantityKinds AreaPresence and Footfall, and add Unit NumPeople.

### PR DESCRIPTION
**Pull request by perkarlberg**
Unclear how NumPeople should be used. If an applicable QUDT exists.

### CODE REVIEW

**Review by hammar — COMMENTED** [review]
Hej,

Det här ser överlag vettigt ut. Några frågor:

1. QUDT har en QuantityKind "Dimensionless", som vi inte har använt, men skulle kunna dra in om vi så önskar, för sådana mätningar som saknar enhet. Typiskt "X stycken av någonting", vid räkning eller liknande. Är det ett intressant alternativ att köra det i stället för "NumPeople"?
2. Vad används enheten "Index" för? Den verkar inte länkad från övriga quantitykinds, och kommentaren är lite svårtydd.
3. Nu ligger ändringarna i Full-ontologin, som ju bara är en "komposition" av REC-modulerna. Jag skulle föreslå att vi lägger ändringarna i Units-modulen i stället, tillsammans med de tidigare definierade quantity kinds och units.
4. Vi har via punning uttryckt enheter både som QUDT units (named individuals) och som OWL datatypes (för att kunna använda dem med data properties). Under förutsättning att vi fortsätter använda enheten NumPeople (se fråga 1 ovan), skall vi också punna dem som datatypes?

Jag kan, efter svar på ovanstående, göra behövda justeringar.

**Comment by hammar** [comment]
Oops, wrote my last comment in Swedish, by habit. Here's a translation to English, for international users: 

"Overall, this looks reasonable. Some questions:

1. QUDT has the QuantityKind "Dimensionless", which we have not used, but could clone if needed, for measurements that lack a unit. E.g., counting "X number of things". Would it make sense to use the quantitykind instead of the custom ones and NumPeople unit?
2. What is the unit "Index" to be used for? It is not linked from any new quantitykinds and its comment is a little difficult to parse
3. Presently the changes are commited to the "full" namespace, which is a composition of REC modules. THey should probably be in the "units" module instead.
4. We utilize punning between QUDT units (named individuals) and OWL datatypes, to support the use of those units as types for data properties. Provided that we do use NumPeople as a unit, should we pun this in the same way?

I can, given answers to the above, implement the required changes"

**Comment by perkarlberg** [comment]
I have addressed 3. move fro full.rdf to units.rdf

**Comment by perkarlberg** [comment]
Regarding
1. Dimensionless.
Until we have another affordance to state what we are measuring, using Dimensionless (essentially "null") would simply mean that we would require informal modelling to make that clear.

Both Number of People and Index would fall under Dimensionless. Until it is addressed elsewhere, we need e.g. Number of People.

2. Index
It is a common occurrence to have a metric which does not have a strict meaning, but where two data points can be compared to each other (a quantity twice as big has an intuitively clear implication) and where the the distinction between zero and non-zero values has an intuitively clear implication. That is the intention with the unit Index.
We could expand it to further distinguish between e.g. an index with baseline 100 (the start or the typical value), an index serving as "a compound measure that aggregates multiple indicators" to differentiate it from Dimensionless.
https://en.wikipedia.org/wiki/Index_(statistics)
https://en.wikipedia.org/wiki/Index_(economics)

**Comment by perkarlberg** [comment]
I believe that both Number of people and Index adds meaning and affordances to RealEstateCore (and to a person or application that tries to interpret objects or data described in RealEstateCore), and that we should include them.

as for punning (4. in your list) I have not done that.

**Comment by hammar** [comment]
I believe this PR is no longer appropriate post REC4. Please reopen if I'm mistaken.

**Pull request closed without merging**
