### PR TITLE
Fix statements about qudt:hasQuantityKind

### PR DESCRIPTION
**Pull request by ektrah**
rec.ttl [currently](https://github.com/RealEstateCore/rec/blob/6dfc0a9671636ca959834a50db45186f6f189231/Source/SHACL/RealEstateCore/rec.ttl) makes some statements about vocabulary from QUDT and GeoJSON. In the case of, for example, `qudt:hasQuantityKind`, these statements have quite drastic implications:

https://github.com/RealEstateCore/rec/blob/6dfc0a9671636ca959834a50db45186f6f189231/Source/SHACL/RealEstateCore/rec.ttl#L20-L24

This implicitly turns every subject of a `qudt:hasQuantityKind` statement (including all the named individuals defined by QUDT for units) into a class, causing a lot of bad punning, and every object in such a statement into an instance of the non-existent class identified by the IRI `<qudt:QuantityKind>`.

[QUDT](https://github.com/qudt/qudt-public-repo/blob/cc3b8a5b3c32ff0b470aba486adac62a9df69c53/schema/SCHEMA_QUDT-v2.1.ttl#L2525-L2531):

```ttl
qudt:hasQuantityKind
  a owl:ObjectProperty ;
  rdfs:isDefinedBy <http://qudt.org/2.1/schema/qudt> ;
  rdfs:label "has quantity kind" ;
  rdfs:range qudt:QuantityKind ;
  owl:inverseOf qudt:isQuantityKindOf ;
.
```

I'd propose to remove all statements about foreign vocabulary entirely to avoid problems like these.

### CODE REVIEW

**Comment by hammar** [comment]
Thanks for noticing and bringing this up! This is probably a remnant of the SHACL <-> DTDL translation pipelines. 

Agree that it needs to be addressed. However, a complete removal of all statements about foreign vocabularies is not tenable at this time given that we need that translation machinery to continue working. As the translation does not (yet) resolve owl:imports statements, some duplication of foreign vocabs is thus still needed. Longer term, a more elegant solution that reduces duplication would of course be preferable.

But regardless, we should not introduce inconsistencies like this one. The offending statement is the rdfs:domain one, line  22 in the excerpt above. I've just confirmed that everything keeps working with that statement removed. If you could update this PR to only remove that statement, I'd be happy to merge it right away.

**Comment by ektrah** [comment]
Thanks for the detailed response! Could the statements about foreign vocabularies be outsourced to a separate file in the same directory? That way, rec.ttl could be kept clean and the translation pipeline would just have to load the two files until a more elegant solution is in place.

**Comment by hammar** [comment]
Pardon the delay in responding, I've been relocating intercontinentally since last responding, so have a little bit of an email backlog.

Since we're already late in shipping 4.0, I'm thinking getting such a fix in isn't top priority; but for a 4.1 release, sure, moving such statements into a separate file and namespace, imported through owl:imports, makes perfect sense.

**Comment by ektrah** [comment]
Done!

What about `geojson:Polygon`? REC currently defines it as a string datatype, while GeoJSON defines it [as a class](https://github.com/geojson/geojson-ld/blob/08b273a273937e33b40d0acd2720cc9e0e702dd6/vocab.rdf#L44-L48) with [a `geojson:coordinates` property](https://github.com/geojson/geojson-ld/blob/08b273a273937e33b40d0acd2720cc9e0e702dd6/vocab.rdf#L82-L87):

https://github.com/RealEstateCore/rec/blob/6dfc0a9671636ca959834a50db45186f6f189231/Source/SHACL/RealEstateCore/rec.ttl#L145-L150

```xml
<rdfs:Class rdf:about="https://purl.org/geojson/vocab#Polygon">
    <rdfs:isDefinedBy rdf:resource="http://purl.org/geojson/vocab#" />
    <rdfs:label xml:lang="en">Polygon</rdfs:label>
    <rdfs:comment xml:lang="en">See RFC 7946 Section 3.1.6.</rdfs:comment>
</rdfs:Class>
...
<rdf:Property rdf:about="https://purl.org/geojson/vocab#coordinates">
    <rdfs:isDefinedBy rdf:resource="http://purl.org/geojson/vocab#" />
    <rdfs:label xml:lang="en">coordinates</rdfs:label>
    <rdfs:comment xml:lang="en">RFC 7946 Section 3.1.1.</rdfs:comment>
</rdf:Property>
```

**Comment by hammar** [comment]
Realized I didn't get back to you on this. It looks good to me. I'll take it to the REC Technical Committee call next week for formal decision. Thanks!

**Comment by hammar** [comment]
Re. that inconsistency on Polygon in SHACL -- yes, should be addressed. Per that link to GeoJSON, there does not seem to be an explicit link b/w Polygon and coordinates, or am I missing something?

**Review by hammar — APPROVED** [review]

**Pull request merged**
